[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
staking_program = "Fg6PaFpoGXkYsidMpWxqSWYg8GbZ7qkWpwfXFZVbA3Jk"

[provider]
cluster = "devnet"
wallet = "../my-solana-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
