[toolchain]
anchor_version = "0.28.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
spl_8004 = "G8iYmvncvWsfHRrxZvKuPU6B2kcMj82Lpcf6og6SyMkW"

[programs.devnet]
spl_8004 = "G8iYmvncvWsfHRrxZvKuPU6B2kcMj82Lpcf6og6SyMkW"

[programs.mainnet]
spl_8004 = "G8iYmvncvWsfHRrxZvKuPU6B2kcMj82Lpcf6og6SyMkW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/bl10buer/Desktop/sp8004/my-solana-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
