[features]
seeds = false
skip-lint = false
[programs.localnet]
spl_8004 = "FX7cpN56T49BT4HaMXsJcLgXRpQ54MHbsYmS3qDNzpGm"
x402_facilitator = "Fma6gBu46bG4SE2rt2QQxUAC9Sc1aFmtELVtwvuJfCQf"

[programs.devnet]
spl_8004 = "FX7cpN56T49BT4HaMXsJcLgXRpQ54MHbsYmS3qDNzpGm"
x402_facilitator = "Fma6gBu46bG4SE2rt2QQxUAC9Sc1aFmtELVtwvuJfCQf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/bl10buer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
