[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.31"

[features]
resolution = true
skip-lint = false

[programs.devnet]
spl_fcp = "A4Ee2KoPz4y9XyEBta9DyXvKPnWy2GvprDzfVF1PnjtR"

[programs.localnet]
spl_fcp = "A4Ee2KoPz4y9XyEBta9DyXvKPnWy2GvprDzfVF1PnjtR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/bl10buer/Desktop/sp8004/my-solana-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
